import { promises as fs } from "fs";
import path from "path";
import chalk from "chalk";
import { generateText } from "ai";
import { z } from "zod";
import yoctoSpinner from "yocto-spinner";
import { renderFileTree, renderSetupCommands, renderError } from "../cli/ui/components.js";

/**
 * Zod schema for structured application generation
 */
const ApplicationSchema = z.object({
  folderName: z.string().default("lumina-app"),
  description: z.string().default("Application generated by Lumina Agent"),
  files: z.array(
    z.object({
      path: z.string(),
      content: z.string(),
    })
  ).min(1),
  setupCommands: z.array(z.string()).default([]),
});

/**
 * Create application files
 */
async function createApplicationFiles(baseDir, folderName, files) {
  const appDir = path.join(baseDir, folderName);

  await fs.mkdir(appDir, { recursive: true });

  for (const file of files) {
    const filePath = path.join(appDir, file.path);
    const fileDir = path.dirname(filePath);

    await fs.mkdir(fileDir, { recursive: true });
    await fs.writeFile(filePath, file.content, "utf8");
  }

  return appDir;
}

/**
 * Fallback parser for raw text responses
 */
function extractJsonFromText(rawText) {
  let cleaned = (rawText || "").trim();
  
  // Remove markdown code blocks if present
  if (cleaned.startsWith("```json")) {
    cleaned = cleaned.slice(7);
  } else if (cleaned.startsWith("```")) {
    cleaned = cleaned.slice(3);
  }
  if (cleaned.endsWith("```")) {
    cleaned = cleaned.slice(0, -3);
  }
  cleaned = cleaned.trim();

  try {
    return JSON.parse(cleaned);
  } catch {
    // Find matching outer braces
    const firstBrace = cleaned.indexOf("{");
    const lastBrace = cleaned.lastIndexOf("}");
    if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
      const jsonCandidate = cleaned.slice(firstBrace, lastBrace + 1);
      return JSON.parse(jsonCandidate);
    }
    throw new Error("Unable to parse structured application JSON from AI output.");
  }
}

/**
 * Generate application using structured output with resilient fallbacks
 */
export async function generateApplication(description, aiService, cwd = process.cwd()) {
  await aiService.ensureApiKey();

  const spinner = yoctoSpinner({
    text: chalk.magenta("Architecting project structure & writing code..."),
    color: "magenta",
  }).start();

  const systemPrompt = `You are Lumina CLI Autonomous Agent, an expert AI Software Architect.
Your task is to generate complete, modern, working applications based on the user's description.

CRITICAL INSTRUCTIONS:
1. You MUST respond with ONLY a valid, complete JSON object matching this exact schema:
{
  "folderName": "kebab-case-project-name",
  "description": "Brief 1-2 sentence description of what this application does",
  "setupCommands": ["open index.html"],
  "files": [
    {
      "path": "relative/file/path.ext",
      "content": "clean, working code content"
    }
  ]
}
2. Include essential files (HTML, CSS, JavaScript/TypeScript, README.md, etc.) needed to run immediately.
3. Write clean, complete, working code.
4. Output RAW JSON ONLY. Do NOT include markdown code blocks or prose. Ensure the JSON is completely closed with valid brackets.`;

  const userPrompt = `Generate a complete application for: "${description}"`;

  const providerOptions = {
    groq: {
      reasoningFormat: "hidden",
      reasoningEffort: "low",
    },
  };

  let application = null;
  let lastError = null;

  // Attempt 1: Generate with primary model
  try {
    const textResult = await generateText({
      model: aiService.model,
      system: systemPrompt,
      prompt: userPrompt,
      maxTokens: 8192,
      temperature: 0.2,
      providerOptions,
    });

    const parsed = extractJsonFromText(textResult.text);
    const validated = ApplicationSchema.parse(parsed);
    application = validated;
  } catch (err1) {
    lastError = err1;

    // Attempt 2: Generate with fallback model (openai/gpt-oss-20b)
    try {
      const fallbackResult = await generateText({
        model: aiService.fallbackModel || aiService.model,
        system: systemPrompt,
        prompt: userPrompt,
        maxTokens: 8192,
        temperature: 0.2,
        providerOptions,
      });

      const parsed = extractJsonFromText(fallbackResult.text);
      const validated = ApplicationSchema.parse(parsed);
      application = validated;
    } catch (err2) {
      lastError = err2;
    }
  }

  spinner.stop();

  if (!application) {
    renderError("Generation failed", lastError?.message || "Failed to generate valid application code.");
    throw lastError || new Error("Generation failed");
  }

  try {
    if (!application.files || application.files.length === 0) {
      throw new Error("No files were generated by the agent");
    }

    if (!application.folderName) {
      application.folderName = "lumina-generated-app";
    }

    console.log(`\n  ${chalk.green.bold("✔ Generated:")} ${chalk.cyan(application.folderName)} (${application.files.length} files)`);
    console.log(`  ${chalk.gray(application.description || "Custom application generated by Lumina Agent")}`);

    // Display project file tree
    renderFileTree(application.files, application.folderName);

    // Create files on disk
    const fileWriteSpinner = yoctoSpinner({
      text: chalk.gray("Writing files to disk..."),
      color: "cyan",
    }).start();

    const appDir = await createApplicationFiles(cwd, application.folderName, application.files);
    fileWriteSpinner.stop();

    console.log(`  ${chalk.green("✔ Files written to:")} ${chalk.underline.white(appDir)}\n`);

    // Display setup commands
    renderSetupCommands(application.setupCommands || ["open index.html"], application.folderName);

    return {
      folderName: application.folderName,
      appDir,
      files: application.files.map((f) => f.path),
      commands: application.setupCommands || [],
      success: true,
    };
  } catch (err) {
    renderError("Generation failed", err.message);
    throw err;
  }
}