import { promises as fs } from "fs";
import path from "path";
import chalk from "chalk";
import { generateObject } from "ai";
import { z } from "zod";
import yoctoSpinner from "yocto-spinner";
import { renderFileTree, renderSetupCommands, renderError } from "../cli/ui/components.js";

/**
 * Zod schema for structured application generation
 */
const ApplicationSchema = z.object({
  folderName: z.string().describe("Kebab-case folder name for the application"),
  description: z.string().describe("Brief description of what was created"),
  files: z
    .array(
      z.object({
        path: z.string().describe("Relative file path (e.g., src/App.jsx)"),
        content: z.string().describe("Complete file content"),
      })
    )
    .describe("All files needed for the application"),
  setupCommands: z
    .array(z.string())
    .describe("Bash commands to setup and run (e.g., npm install, npm run dev)"),
});

/**
 * Create application files
 */
async function createApplicationFiles(baseDir, folderName, files) {
  const appDir = path.join(baseDir, folderName);

  await fs.mkdir(appDir, { recursive: true });

  for (const file of files) {
    const filePath = path.join(appDir, file.path);
    const fileDir = path.dirname(filePath);

    await fs.mkdir(fileDir, { recursive: true });
    await fs.writeFile(filePath, file.content, "utf8");
  }

  return appDir;
}

/**
 * Generate application using structured output
 */
export async function generateApplication(description, aiService, cwd = process.cwd()) {
  const spinner = yoctoSpinner({
    text: chalk.magenta("Architecting project structure & writing code..."),
    color: "magenta",
  }).start();

  try {
    const result = await generateObject({
      model: aiService.model,
      schema: ApplicationSchema,
      prompt: `Create a complete, production-ready application for: ${description}

CRITICAL REQUIREMENTS:
1. Generate ALL files needed for the application to run
2. Include package.json with ALL dependencies and correct versions (if needed)
3. Include README.md with setup instructions
4. Include configuration files (.gitignore, etc.) if needed
5. Write clean, well-commented, production-ready code
6. Include error handling and input validation
7. Use modern JavaScript/TypeScript best practices
8. Make sure all imports and paths are correct
9. NO PLACEHOLDERS - everything must be complete and working
10. For simple HTML/CSS/JS projects, you can skip package.json if not needed

Provide:
- A meaningful kebab-case folder name
- All necessary files with complete content
- Setup commands (for example: cd folder, npm install, npm run dev OR just open index.html)
- Make it visually appealing and functional`,
    });

    spinner.stop();

    const application = result.object;

    if (!application.files || application.files.length === 0) {
      throw new Error("No files were generated by the agent");
    }

    console.log(`\n  ${chalk.green.bold("✔ Generated:")} ${chalk.cyan(application.folderName)} (${application.files.length} files)`);
    console.log(`  ${chalk.gray(application.description)}`);

    // Display project file tree
    renderFileTree(application.files, application.folderName);

    // Create files on disk
    const fileWriteSpinner = yoctoSpinner({
      text: chalk.gray("Writing files to disk..."),
      color: "cyan",
    }).start();

    const appDir = await createApplicationFiles(cwd, application.folderName, application.files);
    fileWriteSpinner.stop();

    console.log(`  ${chalk.green("✔ Files written to:")} ${chalk.underline.white(appDir)}\n`);

    // Display setup commands
    renderSetupCommands(application.setupCommands, application.folderName);

    return {
      folderName: application.folderName,
      appDir,
      files: application.files.map((f) => f.path),
      commands: application.setupCommands || [],
      success: true,
    };
  } catch (err) {
    spinner.stop();
    renderError("Generation failed", err.message);
    throw err;
  }
}